# Generated by Django 4.1.7 on 2023-03-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'CalendarEntry',
                'verbose_name_plural': 'CalendarEntries',
            },
        ),
        migrations.CreateModel(
            name='ProgamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'ProgramEntry',
                'verbose_name_plural': 'ProgramEntries',
            },
        ),
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'WorkoutEntry',
                'verbose_name_plural': 'WorkoutEntries',
            },
        ),
    ]
