# Generated by Django 4.1.7 on 2023-03-04 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_entries', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'WorkoutEntry',
                'verbose_name_plural': 'WorkoutEntries',
            },
        ),
        migrations.CreateModel(
            name='ProgamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_entries', to='programs.program')),
            ],
            options={
                'verbose_name': 'ProgramEntry',
                'verbose_name_plural': 'ProgramEntries',
            },
        ),
        migrations.CreateModel(
            name='CalendarEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CalendarEntry',
                'verbose_name_plural': 'CalendarEntries',
            },
        ),
    ]
